server:
  port: 8010
  forward-headers-strategy: framework
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: business
          uri: lb://business
          predicates:
            - Path=/currencies/**
        - id: eureka
          uri: lb://eureka
          predicates:
            - Path=/eureka/**
  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true